# coding: utf-8

"""
    Instana REST API documentation

    Documentation for INSTANA REST API

    The version of the OpenAPI document: 1.304.1059
    Contact: support@instana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from instana_client.models.monitoring_state import MonitoringState

class TestMonitoringState(unittest.TestCase):
    """MonitoringState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitoringState:
        """Test MonitoringState
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MonitoringState`
        """
        model = MonitoringState()
        if include_optional:
            return MonitoringState(
                has_entities = True,
                host_count = 56,
                serverless_count = 56
            )
        else:
            return MonitoringState(
        )
        """

    def testMonitoringState(self):
        """Test MonitoringState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
